In [1]:
#NumPy is a multidimensional library
#Faster than lists. since numpy uses fixed type hence uses less bytes of memory

In [2]:
import numpy as np

In [12]:
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get dimension of array
a.ndim

1

In [9]:
b.ndim

2

In [10]:
#Get shape
b.shape

(2, 3)

In [13]:
#Get type
a.dtype

dtype('int16')

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
#Get a specific element [r,c]
a[1,5]

13

In [16]:
a[1,-2]

13

In [17]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#Get a specific column
a[:,1:2]

array([[2],
       [9]])

In [19]:
#Getting more elements
a[1,1:6:2]

array([ 9, 11, 13])

In [20]:
#Change an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [23]:
#3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#Get a specific array from the 3D array
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [27]:
#Initalizing different types of arrays

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
6*np.ones((2,3))

array([[6., 6., 6.],
       [6., 6., 6.]])

In [31]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [32]:
#Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
#Random decimel numbers
np.random.rand(4,2)

array([[0.60286281, 0.29310681],
       [0.67969142, 0.12257321],
       [0.55617277, 0.25027518],
       [0.20994783, 0.51660491]])

In [38]:
#Random integer values
np.random.randint(4,7,size = (3,3))

array([[6, 4, 5],
       [6, 6, 5],
       [4, 4, 6]])

In [39]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)

In [41]:
print(r1)

[1 1 1 2 2 2 3 3 3]


In [45]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z #output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
#Copying array is tricky
a = np.array([1,2,3])
a

array([1, 2, 3])

In [47]:
b = a
b

array([1, 2, 3])

In [48]:
b[0] = 100

In [49]:
b

array([100,   2,   3])

In [50]:
print(a)

[100   2   3]


In [51]:
b = a.copy()
b

array([100,   2,   3])

In [52]:
#Mathematics

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a+2

array([3, 4, 5, 6])

In [55]:
a -2

array([-1,  0,  1,  2])

In [56]:
a*2

array([2, 4, 6, 8])

In [57]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [58]:
a**2

array([ 1,  4,  9, 16])

In [59]:
#Take sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [60]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [61]:
a[0]

1

Linear Algebra

In [65]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [67]:
c = np.identity(3)

In [68]:
#Finding the determinant
np.linalg.det(c)

1.0

#### Statistics

In [70]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats, axis = 0)

array([1, 2, 3])

#### Reorganizing Arrays

In [72]:
#Reshape